- name: "Updating apt repo/cache"
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt:
    upgrade: yes
    force_apt_get: yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - rsyslog
    state: latest
  become: true
  become_method: sudo

- name: "Check if JDK 21 Debian package exists"
  stat:
    path: "/tmp/jdk-21_linux-x64_bin.deb"
  register: jdk_package

- name: "Download JDK 21 Debian package"
  get_url:
    url: "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb"
    dest: "/tmp/jdk-21_linux-x64_bin.deb"
  become: true
  when: not jdk_package.stat.exists

- name: "Install JDK 21 Debian package"
  apt:
    deb: "/tmp/jdk-21_linux-x64_bin.deb"
  become: true
  become_method: sudo
  when: not jdk_package.stat.exists

- name: "Clean up JDK 21 Debian package"
  file:
    path: "/tmp/jdk-21_linux-x64_bin.deb"
    state: absent
  become: true
  become_method: sudo
